terminal_background = 'p:t-background'
console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
version = 3
final_space = true

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#24283b'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  terminal-black = '#414868'
  terminal-blue = '#7aa2f7'
  terminal-green = '#73daca'
  terminal-magenta = '#bb9af7'
  terminal-red = '#f7768e'
  terminal-white = '#c0caf5'
  terminal-yellow = '#e0af68'
  white-blue = '#a9b1d6'

[secondary_prompt]
  template = '❯'
  foreground = 'p:terminal-blue'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = 'p:terminal-blue'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' '
    foreground = 'red'
    powerline_symbol = ''
    type = 'root'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = ''
      folder_separator_icon = '/'
      home_icon = ''
      style = 'agnoster'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<red>  {{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<yellow>  {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = 'p:terminal-white'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}', '{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}', '{{ if gt .Behind 0 }}p:celeste-blue{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      github_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:pistachio-green'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:terminal-blue'
    type = 'php'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full }}'
    foreground = 'p:terminal-yellow'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full }}'
    foreground = 'p:terminal-magenta'
    type = 'julia'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full}}'
    foreground = 'p:terminal-red'
    type = 'ruby'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'ﳑ {{ .Full}}'
    foreground = 'p:light-sky-blue'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    foreground = 'p:white-blue'
    type = 'command'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'bash'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    foreground = 'p:pistachio-green'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if .Error }}p:terminal-red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
