#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
terminal_background = 'p:t-background'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'root'
style = 'plain'
powerline_symbol = ''
foreground = 'red'
template = ' '

[[blocks.segments]]
type = 'path'
style = 'plain'
foreground = 'blue'
template = '{{ .Path }}'

[blocks.segments.properties]
folder_icon = ''
folder_separator_icon = '/'
home_icon = ''
style = 'agnoster'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'p:terminal-white'
foreground_templates = [
    '{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-yellow{{ end }}',
    '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}',
    '{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}',
    '{{ if gt .Behind 0 }}p:celeste-blue{{ end }}',
]
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<red>  {{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<yellow>  {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'

[blocks.segments.properties]
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true
github_icon = ' '
branch_icon = ' '

[[blocks]]
type = 'prompt'
alignment = 'right'
overflow = 'hide'

[[blocks.segments]]
type = 'node'
style = 'plain'
foreground = 'p:pistachio-green'
template = ' {{ .Full }} '

[[blocks.segments]]
type = 'php'
style = 'plain'
foreground = 'p:terminal-blue'
template = ' {{ .Full }} '

[[blocks.segments]]
type = 'python'
style = 'plain'
foreground = 'p:terminal-yellow'
template = ' {{ .Full }}'

[[blocks.segments]]
type = 'julia'
style = 'plain'
foreground = 'p:terminal-magenta'
template = ' {{ .Full }}'

[[blocks.segments]]
type = 'ruby'
style = 'plain'
foreground = 'p:terminal-red'
template = ' {{ .Full}}'

[[blocks.segments]]
type = 'go'
style = 'plain'
foreground = 'p:light-sky-blue'
template = 'ﳑ {{ .Full}}'

[[blocks.segments]]
type = 'command'
style = 'plain'
foreground = 'p:white-blue'

[blocks.segments.properties]
command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
shell = 'bash'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground = 'p:pistachio-green'
foreground_templates = ["{{ if .Error }}p:terminal-red{{ end }}"]
template = '❯'
properties.always_enabled = true

[transient_prompt]
foreground = 'p:terminal-blue'
template = '❯ '

[secondary_prompt]
foreground = 'p:terminal-blue'
background = 'transparent'
template = '❯'

[palette]
blue-bell = '#9aa5ce'
blue-black = '#565f89'
celeste-blue = '#b4f9f8'
light-sky-blue = '#7dcfff'
main-bg = '#24283b'
pastal-grey = '#cfc9c2'
pistachio-green = '#9ece6a'
t-background = 'p:main-bg'
terminal-black = '#414868'
terminal-blue = '#7aa2f7'
terminal-green = '#73daca'
terminal-magenta = '#bb9af7'
terminal-red = '#f7768e'
terminal-white = '#c0caf5'
terminal-yellow = '#e0af68'
white-blue = '#a9b1d6'
